"""
Stage 1 seed data — deterministic team and manager profiles.

Coverage: 11 seeded teams + fallback for all others.
Data is sourced from publicly observed World Cup 2022/2026 qualifying patterns
and coach behaviour history. No live data, no APIs.
"""
from __future__ import annotations

from oracle.knowledge.schema import TeamIdentityProfile, ManagerProfile

# ── Team profiles ──────────────────────────────────────────────────────────────

_TEAM_PROFILES: dict[str, dict] = {
    "argentina": {
        "display_name":        "Argentina",
        "primary_archetype":   "counter_attack",
        "secondary_archetype": "possession_control",
        "identity_confidence": 0.88,
        "tempo":               "variable",
        "possession_style":    "balanced",
        "pressing_intensity":  "medium",
        "defensive_block":     "mid_block",
        "transition_tendency": "quick",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "low",
        "risk_profile":        "balanced",
        "known_strengths":     [
            "Elite individual quality (Messi era successor generation)",
            "Lead-protection discipline under Scaloni",
            "Compact defensive shape off the ball",
            "Clinical counter-attacking transitions",
        ],
        "known_weaknesses":    [
            "Defensive vulnerabilities against high-tempo pressing",
            "Dependent on narrow central channels",
            "Set-piece defending can be suspect vs aerial threat",
        ],
    },
    "france": {
        "display_name":        "France",
        "primary_archetype":   "counter_attack",
        "secondary_archetype": "high_press",
        "identity_confidence": 0.86,
        "tempo":               "variable",
        "possession_style":    "balanced",
        "pressing_intensity":  "medium",
        "defensive_block":     "mid_block",
        "transition_tendency": "quick",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "medium",
        "risk_profile":        "conservative",
        "known_strengths":     [
            "World-class pace on the counter (Mbappé-era profile)",
            "Defensive solidity and organisation under Deschamps",
            "Set-piece threat in both boxes",
            "Depth and squad quality across all positions",
        ],
        "known_weaknesses":    [
            "First-half caution can suppress attacking output",
            "Over-reliance on individual brilliance for creativity",
            "Vulnerable to sustained pressing when not fully switched on",
        ],
    },
    "germany": {
        "display_name":        "Germany",
        "primary_archetype":   "high_press",
        "secondary_archetype": "possession_control",
        "identity_confidence": 0.84,
        "tempo":               "high",
        "possession_style":    "dominant",
        "pressing_intensity":  "high",
        "defensive_block":     "high_line",
        "transition_tendency": "quick",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "medium",
        "risk_profile":        "aggressive",
        "known_strengths":     [
            "Organised, high-energy press under Nagelsmann",
            "Technical ball circulation from back",
            "Directional and purposeful attacking patterns",
            "Strong set-piece delivery",
        ],
        "known_weaknesses":    [
            "Energy drop in second half after sustained high press",
            "High defensive line exploitable by pace behind",
            "Susceptible to late goals if press intensity drops",
        ],
    },
    "brazil": {
        "display_name":        "Brazil",
        "primary_archetype":   "possession_control",
        "secondary_archetype": "high_press",
        "identity_confidence": 0.82,
        "tempo":               "high",
        "possession_style":    "dominant",
        "pressing_intensity":  "high",
        "defensive_block":     "high_line",
        "transition_tendency": "quick",
        "set_piece_reliance":  "low",
        "aerial_reliance":     "low",
        "risk_profile":        "aggressive",
        "known_strengths":     [
            "Fluid attacking movement and technical quality",
            "High press creates turnovers in dangerous areas",
            "Wide attacking threat from full-back positions",
            "Ability to control tempo and territory",
        ],
        "known_weaknesses":    [
            "Defensive organisation under counter-attacking pressure",
            "Full-backs caught high on transition",
            "Over-elaborate in final third when simpler option exists",
        ],
    },
    "england": {
        "display_name":        "England",
        "primary_archetype":   "set_piece_heavy",
        "secondary_archetype": "possession_control",
        "identity_confidence": 0.82,
        "tempo":               "medium",
        "possession_style":    "dominant",
        "pressing_intensity":  "medium",
        "defensive_block":     "mid_block",
        "transition_tendency": "measured",
        "set_piece_reliance":  "high",
        "aerial_reliance":     "high",
        "risk_profile":        "conservative",
        "known_strengths":     [
            "Set-piece threat at both ends — elite delivery and aerial power",
            "Strong defensive organisation and structure",
            "Depth of quality across all positions",
            "High converting from corners and free-kicks",
        ],
        "known_weaknesses":    [
            "Open-play creativity can be limited against low blocks",
            "Predictable build-up patterns under pressure",
            "Tendency to invite pressure at tournament level",
        ],
    },
    "spain": {
        "display_name":        "Spain",
        "primary_archetype":   "possession_control",
        "secondary_archetype": "high_press",
        "identity_confidence": 0.90,
        "tempo":               "medium",
        "possession_style":    "dominant",
        "pressing_intensity":  "high",
        "defensive_block":     "high_line",
        "transition_tendency": "measured",
        "set_piece_reliance":  "low",
        "aerial_reliance":     "low",
        "risk_profile":        "balanced",
        "known_strengths":     [
            "Elite possession retention and tiki-taka superiority",
            "Coordinated high press triggers turnovers high up the pitch",
            "Technical quality in tight spaces",
            "Wide overloads via inverted wingers and full-backs",
        ],
        "known_weaknesses":    [
            "Low-block compact defences neutralise possession advantage",
            "Limited aerial threat in both boxes",
            "Slow build-up can be disrupted by physical high press",
        ],
    },
    "uruguay": {
        "display_name":        "Uruguay",
        "primary_archetype":   "high_press",
        "secondary_archetype": "direct_play",
        "identity_confidence": 0.80,
        "tempo":               "high",
        "possession_style":    "pragmatic",
        "pressing_intensity":  "high",
        "defensive_block":     "mid_block",
        "transition_tendency": "quick",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "medium",
        "risk_profile":        "aggressive",
        "known_strengths":     [
            "High-energy press generates chaos and tempo disruption",
            "Physical and aerial threat from set pieces",
            "Experienced defensive core with tactical discipline",
            "Set-piece delivery quality",
        ],
        "known_weaknesses":    [
            "Press can leave gaps in transition when press breaks",
            "Cards risk from high-intensity pressing approach",
            "Attacking creativity limited without Suárez/Cavani era quality",
        ],
    },
    "japan": {
        "display_name":        "Japan",
        "primary_archetype":   "counter_attack",
        "secondary_archetype": "tournament_survival",
        "identity_confidence": 0.80,
        "tempo":               "variable",
        "possession_style":    "reactive",
        "pressing_intensity":  "medium",
        "defensive_block":     "low_block",
        "transition_tendency": "quick",
        "set_piece_reliance":  "low",
        "aerial_reliance":     "low",
        "risk_profile":        "conservative",
        "known_strengths":     [
            "Disciplined defensive shape and low-block organisation",
            "Fast counter-attacking transitions after winning the ball",
            "Second-half tactical adjustments under Moriyasu",
            "High-work-rate pressing windows to disrupt rhythm",
        ],
        "known_weaknesses":    [
            "Aerial disadvantage against physical opponents",
            "Limited scoring against well-organised defences",
            "Counter-attack requires clean ball recovery",
        ],
    },
    "morocco": {
        "display_name":        "Morocco",
        "primary_archetype":   "tournament_survival",
        "secondary_archetype": "counter_attack",
        "identity_confidence": 0.84,
        "tempo":               "low",
        "possession_style":    "reactive",
        "pressing_intensity":  "low",
        "defensive_block":     "low_block",
        "transition_tendency": "quick",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "medium",
        "risk_profile":        "conservative",
        "known_strengths":     [
            "Elite defensive organisation and low-block compactness",
            "Fast, direct counter-attacks through wide channels",
            "Set-piece delivery and aerial threat at both ends",
            "Emotional and atmospheric home-like support generating mentality",
        ],
        "known_weaknesses":    [
            "Limited sustained possession and territorial control",
            "Creativity limited when asked to chase the game",
            "Corners and set pieces against aerial threats",
        ],
    },
    "united_states": {
        "display_name":        "United States",
        "primary_archetype":   "high_press",
        "secondary_archetype": "direct_play",
        "identity_confidence": 0.74,
        "tempo":               "high",
        "possession_style":    "balanced",
        "pressing_intensity":  "high",
        "defensive_block":     "mid_block",
        "transition_tendency": "quick",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "medium",
        "risk_profile":        "aggressive",
        "known_strengths":     [
            "High-energy pressing and physical intensity",
            "Athletic profile across midfield and defence",
            "Direct attacking transitions with pace",
            "Growing technical quality in MLS and European-based players",
        ],
        "known_weaknesses":    [
            "Tactical naivety against established European patterns",
            "Inconsistency in defensive shape against technically superior opponents",
            "Limited experience at major tournament knockout stages",
        ],
    },
    "mexico": {
        "display_name":        "Mexico",
        "primary_archetype":   "possession_control",
        "secondary_archetype": "counter_attack",
        "identity_confidence": 0.76,
        "tempo":               "medium",
        "possession_style":    "balanced",
        "pressing_intensity":  "medium",
        "defensive_block":     "mid_block",
        "transition_tendency": "hybrid",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "low",
        "risk_profile":        "balanced",
        "known_strengths":     [
            "Technical quality and positional organisation",
            "Tournament experience and knockout pragmatism",
            "Creative midfield play through tight spaces",
        ],
        "known_weaknesses":    [
            "Historically underperforms in Round of 16 knockout (fifth game syndrome)",
            "Limited clinical finishing against top defences",
            "Can be too conservative when a goal is needed",
        ],
    },
    "portugal": {
        "display_name":        "Portugal",
        "primary_archetype":   "counter_attack",
        "secondary_archetype": "set_piece_heavy",
        "identity_confidence": 0.80,
        "tempo":               "variable",
        "possession_style":    "balanced",
        "pressing_intensity":  "medium",
        "defensive_block":     "mid_block",
        "transition_tendency": "quick",
        "set_piece_reliance":  "high",
        "aerial_reliance":     "high",
        "risk_profile":        "balanced",
        "known_strengths":     [
            "Individual quality across attacking positions",
            "Set-piece threat through delivery and aerial power",
            "Defensive organisation and counter-attacking speed",
        ],
        "known_weaknesses":    [
            "Post-Ronaldo era identity still consolidating",
            "Defensive vulnerability when chasing games",
        ],
    },
    "netherlands": {
        "display_name":        "Netherlands",
        "primary_archetype":   "high_press",
        "secondary_archetype": "possession_control",
        "identity_confidence": 0.80,
        "tempo":               "high",
        "possession_style":    "dominant",
        "pressing_intensity":  "high",
        "defensive_block":     "high_line",
        "transition_tendency": "quick",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "medium",
        "risk_profile":        "aggressive",
        "known_strengths":     [
            "Organised pressing and high defensive line",
            "Technical quality and positional play",
            "Set-piece threat through delivery quality",
        ],
        "known_weaknesses":    [
            "High line vulnerable to pace in behind",
            "Inconsistency under pressure at tournament level",
        ],
    },
    "croatia": {
        "display_name":        "Croatia",
        "primary_archetype":   "possession_control",
        "secondary_archetype": "tournament_survival",
        "identity_confidence": 0.78,
        "tempo":               "medium",
        "possession_style":    "dominant",
        "pressing_intensity":  "medium",
        "defensive_block":     "mid_block",
        "transition_tendency": "measured",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "medium",
        "risk_profile":        "conservative",
        "known_strengths":     [
            "World-class midfield control through Modrić-generation axis",
            "Tournament experience and never-say-die mentality",
            "Late-game resilience and penalty shootout composure",
        ],
        "known_weaknesses":    [
            "Ageing squad with reduced high-press capability",
            "Reduced scoring output in post-Mandžukić era",
        ],
    },
    "senegal": {
        "display_name":        "Senegal",
        "primary_archetype":   "direct_play",
        "secondary_archetype": "high_press",
        "identity_confidence": 0.74,
        "tempo":               "high",
        "possession_style":    "pragmatic",
        "pressing_intensity":  "high",
        "defensive_block":     "mid_block",
        "transition_tendency": "quick",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "high",
        "risk_profile":        "aggressive",
        "known_strengths":     [
            "Physical and athletic profile throughout the squad",
            "Direct attacking threat with Mané-era successor generation",
            "Set-piece aerial threat",
        ],
        "known_weaknesses":    [
            "Tactical discipline can break down under pressure",
            "Dependence on individual moments rather than systematic patterns",
        ],
    },
    "south_korea": {
        "display_name":        "South Korea",
        "primary_archetype":   "counter_attack",
        "secondary_archetype": "tournament_survival",
        "identity_confidence": 0.72,
        "tempo":               "high",
        "possession_style":    "reactive",
        "pressing_intensity":  "medium",
        "defensive_block":     "low_block",
        "transition_tendency": "quick",
        "set_piece_reliance":  "low",
        "aerial_reliance":     "low",
        "risk_profile":        "conservative",
        "known_strengths":     [
            "Pace and directness on counter-attacks",
            "Collective work ethic and discipline",
            "Inspired tournament upsets (2002, 2022 legacy)",
        ],
        "known_weaknesses":    [
            "Aerial and physical weakness vs top European nations",
            "Limited output against organised low blocks",
        ],
    },
    "australia": {
        "display_name":        "Australia",
        "primary_archetype":   "direct_play",
        "secondary_archetype": "high_press",
        "identity_confidence": 0.68,
        "tempo":               "high",
        "possession_style":    "pragmatic",
        "pressing_intensity":  "high",
        "defensive_block":     "mid_block",
        "transition_tendency": "quick",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "high",
        "risk_profile":        "aggressive",
        "known_strengths":     [
            "Physical intensity and aerial threat",
            "Direct forward play through pace channels",
        ],
        "known_weaknesses":    [
            "Technical limitations vs elite possession teams",
            "Defence can be exposed at the highest level",
        ],
    },
    "colombia": {
        "display_name":        "Colombia",
        "primary_archetype":   "possession_control",
        "secondary_archetype": "counter_attack",
        "identity_confidence": 0.72,
        "tempo":               "medium",
        "possession_style":    "balanced",
        "pressing_intensity":  "medium",
        "defensive_block":     "mid_block",
        "transition_tendency": "hybrid",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "medium",
        "risk_profile":        "balanced",
        "known_strengths":     [
            "Technical quality and creative midfield play",
            "Dangerous on the counter from deep positions",
        ],
        "known_weaknesses":    [
            "Defensive organisation at top European level",
            "Inconsistent big-game mentality",
        ],
    },
    "ecuador": {
        "display_name":        "Ecuador",
        "primary_archetype":   "direct_play",
        "secondary_archetype": "tournament_survival",
        "identity_confidence": 0.66,
        "tempo":               "medium",
        "possession_style":    "pragmatic",
        "pressing_intensity":  "medium",
        "defensive_block":     "mid_block",
        "transition_tendency": "measured",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "high",
        "risk_profile":        "balanced",
        "known_strengths":     [
            "Physical aerial threat especially from Valença-type centre-backs",
            "Compact and organised defensive structure",
        ],
        "known_weaknesses":    [
            "Limited technical quality against elite possession teams",
            "Creative output constrained when asked to attack",
        ],
    },
    "switzerland": {
        "display_name":        "Switzerland",
        "primary_archetype":   "tournament_survival",
        "secondary_archetype": "counter_attack",
        "identity_confidence": 0.76,
        "tempo":               "medium",
        "possession_style":    "balanced",
        "pressing_intensity":  "medium",
        "defensive_block":     "mid_block",
        "transition_tendency": "measured",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "medium",
        "risk_profile":        "conservative",
        "known_strengths":     [
            "Defensive solidity and tactical discipline",
            "Counter-attacking efficiency under Yakin",
            "Tournament resilience and knockout experience",
        ],
        "known_weaknesses":    [
            "Limited ambition when a draw serves their qualification needs",
            "Attacking quality insufficient to test elite defences",
        ],
    },
    "belgium": {
        "display_name":        "Belgium",
        "primary_archetype":   "possession_control",
        "secondary_archetype": "counter_attack",
        "identity_confidence": 0.74,
        "tempo":               "variable",
        "possession_style":    "balanced",
        "pressing_intensity":  "medium",
        "defensive_block":     "mid_block",
        "transition_tendency": "quick",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "medium",
        "risk_profile":        "balanced",
        "known_strengths":     [
            "Individual quality in a transitional squad",
            "Experience from Golden Generation era persisting",
        ],
        "known_weaknesses":    [
            "Post-Golden Generation squad still finding identity",
            "Defensive vulnerabilities if pressed high",
        ],
    },
    "canada": {
        "display_name":        "Canada",
        "primary_archetype":   "high_press",
        "secondary_archetype": "direct_play",
        "identity_confidence": 0.70,
        "tempo":               "high",
        "possession_style":    "pragmatic",
        "pressing_intensity":  "high",
        "defensive_block":     "mid_block",
        "transition_tendency": "quick",
        "set_piece_reliance":  "medium",
        "aerial_reliance":     "medium",
        "risk_profile":        "aggressive",
        "known_strengths":     [
            "High-energy team press inspired by Davies generation",
            "Direct and ambitious attacking outlook",
        ],
        "known_weaknesses":    [
            "Defensive frailties at the highest level",
            "Limited big-tournament experience",
        ],
    },
}

# ── Manager profiles ───────────────────────────────────────────────────────────

_MANAGER_PROFILES: dict[str, dict] = {
    "argentina": {
        "manager_id":          "scaloni",
        "name":                "Lionel Scaloni",
        "team_id":             "argentina",
        "profile_confidence":  0.85,
        "preferred_style":     "counter_attack",
        "first_half_behavior": "cautious",
        "lead_behavior":       "protect",
        "trailing_behavior":   "patient",
        "substitution_pattern": "late",
        "known_patterns": [
            {
                "pattern":          "lead_protection",
                "description":      "When ahead, Scaloni compresses shape and absorbs pressure to protect leads.",
                "supports_markets": ["under_goals", "btts_no", "1x2_home"],
                "confidence":       0.82,
            },
            {
                "pattern":          "second_half_defensive_block",
                "description":      "Argentina under Scaloni tend to lower defensive intensity in second half when ahead.",
                "supports_markets": ["under_goals_second_half"],
                "confidence":       0.74,
            },
        ],
    },
    "france": {
        "manager_id":          "deschamps",
        "name":                "Didier Deschamps",
        "team_id":             "france",
        "profile_confidence":  0.87,
        "preferred_style":     "counter_attack",
        "first_half_behavior": "cautious",
        "lead_behavior":       "protect",
        "trailing_behavior":   "open_up",
        "substitution_pattern": "reactive",
        "known_patterns": [
            {
                "pattern":          "first_half_caution",
                "description":      "Deschamps' France typically open cautiously, suppressing first-half goal output.",
                "supports_markets": ["under_goals", "first_half_under"],
                "confidence":       0.84,
            },
            {
                "pattern":          "late_game_resilience",
                "description":      "France grind results through organisation and individual moments rather than sustained attack.",
                "supports_markets": ["1x2_home", "under_goals"],
                "confidence":       0.76,
            },
        ],
    },
    "germany": {
        "manager_id":          "nagelsmann",
        "name":                "Julian Nagelsmann",
        "team_id":             "germany",
        "profile_confidence":  0.80,
        "preferred_style":     "high_press",
        "first_half_behavior": "attacking",
        "lead_behavior":       "extend",
        "trailing_behavior":   "open_up",
        "substitution_pattern": "early",
        "known_patterns": [
            {
                "pattern":          "press_energy_cliff",
                "description":      "Germany's high press drops intensity in second half, creating late-game volatility.",
                "supports_markets": ["over_goals_second_half", "late_goal_risk", "cards_over"],
                "confidence":       0.78,
            },
            {
                "pattern":          "high_line_exposure",
                "description":      "Nagelsmann's high defensive line leaves space behind for fast opponents.",
                "supports_markets": ["over_goals", "btts_yes"],
                "confidence":       0.72,
            },
        ],
    },
    "uruguay": {
        "manager_id":          "bielsa",
        "name":                "Marcelo Bielsa",
        "team_id":             "uruguay",
        "profile_confidence":  0.82,
        "preferred_style":     "high_press",
        "first_half_behavior": "attacking",
        "lead_behavior":       "extend",
        "trailing_behavior":   "open_up",
        "substitution_pattern": "early",
        "known_patterns": [
            {
                "pattern":          "high_press_chaos",
                "description":      "Bielsa's extreme pressing creates a chaotic, high-tempo match with elevated card and corner risk.",
                "supports_markets": ["cards_over", "corners_over", "first_half_tempo"],
                "confidence":       0.80,
            },
            {
                "pattern":          "press_exhaustion",
                "description":      "Bielsa teams often fade in the second half after sustained press intensity.",
                "supports_markets": ["over_goals_second_half", "late_equalizer"],
                "confidence":       0.72,
            },
        ],
    },
    "morocco": {
        "manager_id":          "regragui",
        "name":                "Walid Regragui",
        "team_id":             "morocco",
        "profile_confidence":  0.84,
        "preferred_style":     "tournament_survival",
        "first_half_behavior": "cautious",
        "lead_behavior":       "protect",
        "trailing_behavior":   "patient",
        "substitution_pattern": "late",
        "known_patterns": [
            {
                "pattern":          "low_block_discipline",
                "description":      "Regragui's Morocco maintain elite low-block compactness, suppressing opponent shot quality.",
                "supports_markets": ["under_goals", "btts_no", "corners_against"],
                "confidence":       0.86,
            },
            {
                "pattern":          "counter_trigger",
                "description":      "When the block holds, Morocco unleash quick counters through wide channels.",
                "supports_markets": ["1x2_away_value", "btts_no"],
                "confidence":       0.74,
            },
        ],
    },
}


# ── Fallback profile ───────────────────────────────────────────────────────────

def _make_fallback(team_id: str) -> TeamIdentityProfile:
    display = team_id.replace("_", " ").title()
    return TeamIdentityProfile(
        team_id=team_id,
        display_name=display,
        primary_archetype="unknown",
        secondary_archetype="none",
        identity_confidence=0.30,
        tempo="medium",
        possession_style="balanced",
        pressing_intensity="medium",
        defensive_block="mid_block",
        transition_tendency="measured",
        set_piece_reliance="medium",
        aerial_reliance="medium",
        risk_profile="balanced",
        known_strengths=[],
        known_weaknesses=[],
        profile_source="fallback",
    )


# ── Public loaders ─────────────────────────────────────────────────────────────

def get_team_profile(team_id: str) -> TeamIdentityProfile:
    """Return seed profile or fallback for unknown teams."""
    raw = _TEAM_PROFILES.get(team_id)
    if raw is None:
        return _make_fallback(team_id)
    return TeamIdentityProfile(
        team_id=team_id,
        profile_source="seed_v1",
        **raw,
    )


def get_manager_profile(team_id: str) -> ManagerProfile | None:
    """Return manager profile for the given team, or None if not seeded."""
    raw = _MANAGER_PROFILES.get(team_id)
    if raw is None:
        return None
    return ManagerProfile(**raw)


def list_seeded_teams() -> list[str]:
    return list(_TEAM_PROFILES.keys())
